# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69fa39e93bb6fda665f32778910d8bc3a6151bec802b153aefc54e1436655b939c442fadd87f12f23945a461b6015ca4cad56280fef00f96bdfc23bc51af4f39

test:
  secret_key_base: 0dac807114ac59f3346095870ffa8955f7a3e36b0088bc8a03ee57a06bc996a9c152b7fbb0a2aa64852f63e0c438a81959f20e0533336dfa7839965419cb9d10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
